- agent/research_agent.py
In windows users may receive an error when the directory name contains question marks or other reserved characters that may work in other systems.
Changed the directory name to contain ascii chars only.
> Changing the setter of directory_name attribute

- Dockerfile
- actions/web_scrape.py
The root Dockerfile is missing the Chrome & Chrome-Driver dependencies - so it will only run in dev mode (local machine). 
The fix in this branch will enable you to publish the Docker image on ubuntu. Without the fix, the scraper fails in Production.
From my research, Chrome & Chrome Driver should be the same version. (This branch contains the latest stable versions of both)
Tested locally on Windows - with VScode ssh-ed into server.
Tested on Ubuntu 22.10 - see image below for Digital Ocean droplet size.
You can view the demo with this branch at: https://gptresearcher.gptbud.com
> Host on linux

- actions/web_scrape.py
.add_experimental_option exists only in chromeDrive, this line causes errors logged when users use other drivers e.g firefox.
> .add_experimental_option exists only in ChromeDrive

- client/index.html
A missing `GPTResearcher.` before the function call prevented the copy to clipboard function from being called.
> Fix copy to clipboard not working

- Dockerfile
- actions/web_scrape.py
Fixes #227 
- Adds firefox and geckodriver to the dockerfile
- Replaces `GeckoDriverManager().install()` with installing geckodriver in the dockerfile
> Fixes: can't run with firefox as selenium browser

- gpt_researcher/master/functions.py
- gpt_researcher/retrievers/__init__.py
- gpt_researcher/retrievers/serpapi/serpapi.py
- gpt_researcher/retrievers/serper/serper.py
Background: [PR 237](https://github.com/assafelovic/gpt-researcher/pull/237) introduced a mix-up, it replaced the correct code for the Google Serper retriever (serper.dev) with code for SerpApi (serpai.com). It looks like the author of the PR may have confused one for the other and thought that the existing correct code was a bug.
This PR:
- brings back the correct code (with small improvements)
- adds the SerApi code from PR 237 as a separate retriever (although that code appears to have an issue, as I noted in the code itself, thus for now I didn't fully enable that retriever)
- resolves a couple of naming issues (e.g. 'serp' vs 'googleSerp' as the name of the retriever)
> Fix serper retriever

- README.md
When I copy the command on the README file:
I see the $ sign also gets copied to the clipboard:
This throws an error when you directly run the command in the terminal.
Removing the $ symbol makes the commands easier to copy-paste.
> Remove $ from terminal commands in README.md

- config.json
- gpt_researcher/config/config.py
- gpt_researcher/master/agent.py
- gpt_researcher/memory/embeddings.py
Introduce support for additional embedding models, such as Hugging Face, MixTRAL, Ollama, etc., allowing users to select their preferred model in the config.json file simply. Any model supported by [langchain embedding](https://python.langchain.com/docs/integrations/text_embedding) can be added easily.
Particularly beneficial for users who do not have access to the OpenAI API, like me XD.
> Add support for various embedding provider

- pyproject.toml
Currently, cannot start project if installed with `poetry install`
> fix: add lxml with html_clean extra to pyproject.toml

- gpt_researcher/master/prompts.py
While reviewing the prompts, I noticed that on a few prompts the parameter `total_words` is not being used.
Let me know if this is ok to merge or if it requires additional changes
> fix: Use total_words parameters in the prompts

- docs/docs/gpt-researcher/pip-package.md
Pip Documentation is outdated. And still uses `researcher.run()`
Fixed that.
> corrected documentation for pip-usage

- gpt_researcher/memory/embeddings.py
Updated OpenAI embeddings to new `text-embedding-3-small` model.
Information about the new model from [OpenAI docs](https://openai.com/index/new-embedding-models-and-api-updates/):
text-embedding-3-small is our new highly efficient embedding model and provides a significant upgrade over its predecessor, the text-embedding-ada-002 model released in [December 2022](https://openai.com/index/new-and-improved-embedding-model/). 
**Stronger performance.** Comparing text-embedding-ada-002 to text-embedding-3-small, the average score on a commonly used benchmark for multi-language retrieval ([MIRACL](https://github.com/project-miracl/miracl)) has increased from 31.4% to 44.0%, while the average score on a commonly used benchmark for English tasks …
> modified to new cheaper OpenAI embedding

- docker-compose.yml
Fix 'docker-compose up --build' command for docs
> remove DOC_Path from docker-compose - rely on .env instead

- gpt_researcher/llm_provider/openai/openai.py
Pydantic alias 'base_url' for the field 'openai_api_base' is not working as expected for assignments outside the constructor, so changed the alias to the original field name for alternative OpenAI base_url.
Fix for the issue #511
> Fix Pydantic validation of base_url assignment for ChatOpenAI model

- gpt_researcher/llm_provider/__init__.py
- gpt_researcher/llm_provider/groq/groq.py
- gpt_researcher/master/prompts.py
- gpt_researcher/utils/llm.py
- requirements.txt
Hi @assafelovic 
This pull request implements the `GroqProvider` class, following the coding patterns defined in `OpenAIProvider`. 
`GroqProvider` enables easy access to the below LLMs:
- Llama3-70b-8192
- Llama3-8b-8192
- Gemma-7b-it
- Mixtral-8x7b-32768
I have tested the changes using the local client and the examples/sample_report.py program with simple queries and can confirm positive results.
The __Llama3 models__ work well but are constrained by the current 8K token window.
__Gemma__ and __Mixtral__ also run to completion with satisfactory results on simple queries even though they refuse to generate valid JSON to establish the "agent_role_prompt." (Note: I tried minor modifications to the auto_agent_instructions prompt but did not get positive results.) 
Overall, the models work …
> Implemented GroqProvider

- README.md
Fix issue with `custom_report` in `write_report` method
- Ensure `report` variable is assigned correctly for `custom_report`.
- Added call to `generate_report` within the `custom_report` block to prevent "local variable 'report' referenced before assignment" error.
This fix ensures that all report types, including `custom_report`, are handled consistently without runtime errors.
> Fix issue with custom_report in write_report method

- Dockerfile
In this updated Dockerfile, the build-essential package is installed, which includes make and other necessary tools for building C/C++ libraries.
After merging, `docker-compose up --build` should work as expected again. This should resolve the issue with the make command not being found
> resolve the issue with the make command not being found when loading docker container

- README.md
Replace the URL giving **Page Not Found** with the correct URL.
[Incorrect URL](https://docs.gptr.dev/docs/gpt-researcher/agent_frameworks)
[Correct URL](https://docs.gptr.dev/docs/gpt-researcher/langgraph)
> Fix[readme]: Page Not Found

- gpt_researcher/llm_provider/azureopenai/azureopenai.py
The original AzureOpenAIProvier class has the deployment name arguments, but in high level llm calls (get_llm) is using the model as interface name.
This needs to be changed, aka AzureOpenAIProvider should have the model argument instead of 
```
File "/home/xpe1szh/miniconda3/envs/gpt-research/lib/python3.10/site-packages/fastapi/routing.py", line 348, in app
await dependant.call(**values)
File "/home/xpe1szh/repo-gh/gpt-researcher/backend/server.py", line 53, in websocket_endpoint
report = await manager.start_streaming(task, report_type, report_source, websocket)
File "/home/xpe1szh/repo-gh/gpt-researcher/backend/websocket_manager.py", line 57, in start_streaming
report = await run_agent(task, report_type, report_source, websocket)
File …
```
> change deployment name to model to fix the init of the azureopenai model

- gpt_researcher/master/actions.py
- requirements.txt
Many of my ollama models are outputting slightly malformed json which was causing exceptions during searches.
This was happening on over 50% of queries, but this small patch resolved
> use repair_json() on output of sub_queries to stop exceptions on local models

- gpt_researcher/llm_provider/huggingface/huggingface.py
This could also be done for other providers, but huggingface is particularly heavy to install due to dependencies on torch &more, so kept it to that for now.
> Lazily import langchain-huggingface to avoid obligatory install

- docs/docs/gpt-researcher/introduction.md
let's get started link was broken and led to:
https://docs.gptr.dev/gpt-researcher/getting-started 
this causes a 404 error, instead it should lead to:
https://docs.gptr.dev/docs/gpt-researcher/getting-started
> Update introduction.md fixing broken link

- gpt_researcher/context/compression.py
- gpt_researcher/master/agent.py
The agent calls a few blocking operations on the main event loop which makes the uvicorn server unresponsive. (can be witnessed by trying to load the Web UI in another tab while the agent is running) By moving these operations to threads, the event loop is kept free to take on other tasks.
> Move blocking operations to threads

- gpt_researcher/llm_provider/ollama/ollama.py
- gpt_researcher/utils/llm.py
openai_api_key is not required for OllamaProvider. Currently, we get this error when using GPTR with Ollama:
```bash
INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
File "/usr/src/app/gpt_researcher/master/actions.py", line 91, in choose_agent
response = await create_chat_completion(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/app/gpt_researcher/utils/llm.py", line 88, in create_chat_completion
provider = get_llm(llm_provider, model=model, temperature=temperature, max_tokens=max_tokens, openai_api_key=openai_api_key, **(llm_kwargs or {}))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/app/gpt_researcher/utils/llm.py", line 51, in …
```
> Fix ollamaprovider error

- gpt_researcher/master/actions.py
- gpt_researcher/master/agent.py
- gpt_researcher/retrievers/searx/searx.py
- gpt_researcher/utils/llm.py
These were the changes I had to make to be able to run with ollama and searx.
removing hardcoded openai and Tavily dependencies.
That should NOT break anything, but I have'nt been able to test with anything other that ollama & searx/duckduckgo.
> Bugfix: Enable use of ollama and searx without commercial services / Remove openai and tavily dependency (and fixed missing tone errors)

- gpt_researcher/master/actions.py
- gpt_researcher/master/agent.py
- multi_agents/agents/master.py
In the previous version, the default case in get_retriever() meant
that setting retriever from config (as opposed to the header) was
ignored, and instead, the default (tavily) retriever was chosen.
Added new function to get the default retriever.
Sanitizing function replaces the slashes in the path, which is
most likely undesired. Discussed in 
https://github.com/assafelovic/gpt-researcher/pull/679#issuecomment-2235946414
> Fixes: Default retriever, sanitizing

- .env.example
- docs/docs/gpt-researcher/retrievers.md
- gpt_researcher/config/config.py
- gpt_researcher/master/actions.py
- gpt_researcher/master/agent.py
This pull request enhances GPTResearcher by introducing support for selecting multiple retrievers. The following changes have been made:
- Updated the `.env.example` file to include configurations for both `RETRIEVER` and `RETRIEVERS`.
1. If `RETRIEVER` is set and `RETRIEVERS` is not set, the value of `RETRIEVER` will be used by default.
2. If `RETRIEVERS` is set, the values specified in `RETRIEVERS` will be used, separated by commas.
3. If both are set, `RETRIEVERS` takes precedence.
- Refactored the search result handling to iterate through multiple retrievers and combine their results.
- Updated the configuration to support multiple retrievers by parsing the `RETRIEVERS` environment variable.
- Added helper functions to manage the retrieval process based on the new configuration.
These …
> Add Support for Multiple Retrievers in GPTR

- backend/server.py
- multi_agents/agents/human.py
- multi_agents/frontend/app/page.tsx
- multi_agents/frontend/components/HumanFeedback.tsx
In progress: Needs some more research into how to pass the websocket back to the relevant function (or stage of the flow) to continue the flow on the backend with the human feedback
> WIP: Human in the loop - frontend support

- requirements.txt
- To fix the json5 library not found, add the library to the requirements file.
> [Fix] No module named 'json5'

- gpt_researcher/master/prompts.py
Resolved a `TypeError` that occurred when generating custom reports, caused by the `generate_custom_report_prompt()` function receiving an unexpected keyword argument 'tone'. The issue was due to the absence of the 'tone' parameter in the function definition, which has now been added to ensure correct functionality.
> Fix TypeError in custom reports due to missing 'tone' parameter

- requirements.txt
Discovered that a clean download of the current master brach bwill not allow running `python -m uvicorn main:app --reload` as `langhgraph` was missing.
> fix: added missing langgraph to requirements.txt

- multi_agents/agents/editor.py
- multi_agents/agents/human.py
- multi_agents/agents/reviewer.py
- multi_agents/agents/reviser.py
- multi_agents/agents/utils/llms.py
- multi_agents/agents/writer.py
This addresses issue #764 
Changed the `call_llm`  function 
- to re-use the "select the right model from .env" from GPT-R
- Changed the handling of the response in "json" mode to return a parsed json, else return the response as is.
- Simplified the function to take less params, as most can/should be configured either via task or .env (Config() from GPTR, or config_file)
@ElishaKay, I tried to touch as little code as possible, but also don't fully grasp the langgraph logic you built. Please check If I broke something essential.
I can run and generate reports using multi-agent with AzureOpenAI now. (but my report switched from English to Spanish in the last agent -- my colleagues tell me GPT-4o likes to speak Spanish more than English and often does that.)
> multi-agent approach should now use .env file for config of llm

- multi_agents/requirements.txt
multi_agents/requirements.txt was missing loguru.
Someone will probably find this before me, but I figured see something say something.
> multi_agents/requirements.txt was missing loguru

- requirements.txt
There is no such PyPi package as logurun. Changes to loguru, consistent with multi_agents/requirements.txt
> Fix package name from logurun to loguru in requirements.txt. Fixes #809

- gpt_researcher/llm_provider/generic/base.py
How to reproduct: Ask a random question and the result shown in the webUI does not contain the last few lines when compare to the PDF.
Description: when the model output chunks of messages, the chunks are combined to paragraphs and send to websocket. However, the last paragraph is never sent (if the last paragraph does not contain \n). My change check if paragraph is not empty to send the last paragraph out.
> Fix Last Paragraph is not Sent to Websocket

- gpt_researcher/README.md
I’ve added a section at the end of the `gpt_researcher/README.md` to address frequent questions about setting up custom configurations. Noticing that many users had queries on this topic, I included detailed instructions for creating and using a custom JSON configuration file.
> Adding Custom Configuration Setup Instructions to GPTR

- gpt_researcher/master/prompts.py
This PR fixes a SyntaxError in `/usr/src/app/gpt_researcher/master/prompts.py` that was causing the application to fail on startup. The error was due to conflicting quotes in an f-string used to format the current date.
- Modified line 33 in `/usr/src/app/gpt_researcher/master/prompts.py` to resolve quote conflicts in the f-string.
> Fix SyntaxError in prompts.py due to conflicting quotes in f-string

- backend/report_type/detailed_report/detailed_report.py
- gpt_researcher/llm_provider/generic/base.py
The GPT Researcher tool was unable to complete research tasks with Ollama when run inside a Docker container on WSL2. This issue has been resolved by addressing two key problems.
By default, the tool attempted to connect to `localhost` instead of using the provided base URL for Ollama. We have updated the code to use the provided base URL when running in a Docker container.
When generating detailed reports, we encountered an error because `get_subtopics` was sending a list instead of a dictionary. This has been corrected by updating the `get_subtopics` function to return a dictionary.
The following changes have been made to address these issues:
* Updated `base.py` to use the provided Ollama base URL.
* Modified the `get_subtopics` function in `report.py` to return a dictionary instead of …
> Ollama fixes

- gpt_researcher/llm_provider/generic/base.py
Title: Fix missing "import os" in base.py (Ollama Integration)
Steps To Reproduce: When trying to use Ollama integration features, an ImportError occurs due to missing "os" import in base.py.
Fix Details: Added import os at the beginning of the file. This ensures that all necessary modules are imported before they're used within other parts of the codebase.
> Fixing the missing "os" import for base.py

- docs/docs/gpt-researcher/getting-started/linux-deployment.md
Users cannot upload larger documents. The default size is less than 1MB. To solve this, server nginx should be updated with `client_max_body_size 64M;`. I added it to the documentation.
> Users can upload larger files

- multi_agents/agents/utils/utils.py
Resolves the `SyntaxWarning` when starting up
```apl
INFO:     Will watch for changes in these directories: ['/Users/samy/Dropbox/Mac/Documents/Code/gpt/gpt-researcher']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [85658] using StatReload
/Users/samy/Dropbox/Mac/Documents/Code/gpt/gpt-researcher/multi_agents/agents/utils/utils.py:4: SyntaxWarning: invalid escape sequence '\ '
"""
```
> utils.py: resolve SyntaxWarning

- gpt_researcher/memory/embeddings.py
This pull request updates the Hugging Face embeddings in the project to use the all-MiniLM-L6-v2 model from the sentence-transformers library. The previous implementation did not specify any specific model (since no specific model is passed, it might load a default model), so this change ensures that we use all-MiniLM-L6-v2, which is more efficient in terms of performance and accuracy.
Why all-MiniLM-L6-v2 ?
- The all-MiniLM-L6-v2 model provides faster performance , making it quicker to handle large corpus.
- This model is known for generating high-quality embeddings, improving the overall accuracy of similarity and other tasks.
- all-MiniLM-L6-v2 is known for improved performance, this model provides a good balance between speed and effectiveness.
> Updated Hugging Face embeddings to use all-MiniLM-L6-v2

- gpt_researcher/config/variables/base.py
To fix the bug indicated in https://github.com/assafelovic/gpt-researcher/issues/901 and https://github.com/assafelovic/gpt-researcher/issues/900
> Hotfix: Update base.py

- Dockerfile
- single layer installation
- no cache with `pip`
- consolidation of python dependencies
- removal of temp files
As you can see on the image below, the last two builds are with the current state of `Dockerfile`, and the first two are with the improvements. There is significant build time improvement and slight image size reduction for `gpt-researcher` image, about 300-400MB. I used `docker compose up -d --build`.
> refactor(Dockerfile): optimize Dockerfile structure and layers

- README.md
Corrected "the the" to "the" in [README.md].
Removing the extra "the".
This pull request addresses a minor typo found in the repository. The typo has been corrected to improve clarity and maintain the quality of the documentation.
This change is purely cosmetic and does not affect functionality.
> Doc: Typo Fix

- gpt_researcher/memory/embeddings.py
this is causing the no content generation when google/huggingace are used as llm/embedding models
> update langchain huggingface embedding

- gpt_researcher/retrievers/pubmed_central/pubmed_central.py
By default, it looks like pubmed_central results are sorted by latest. This can produce results that are not helpful. 
The added sort=relevance parameter can be tried with a link like this: 
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pmc&term=what+are+the+physiological+functions+of+calcium+AND+free+fulltext%5Bfilter%5D&retmax=3&usehistory=y&retmode=json&sort=relevance
> Sort pubmed_central search results by relevance versus default newest

- gpt_researcher/skills/context_manager.py
Fixes a bug when calling GPTResearcher with report_source='langchain_vectorstore'. 
code to test: 
```
import asyncio 
from gpt_researcher import GPTResearcher
import os 
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings 
from langchain_community.vectorstores import FAISS 
from langchain_core.documents import Document 
from gpt_researcher.document import DocumentLoader, LangChainDocumentLoader 
os.environ['OPENAI_API_KEY']="add your key"
os.environ['TAVILY_API_KEY']="add your key"
async def main():
document_data = await DocumentLoader("./my-docs").load()
langchain_docs = [Document(page_content=item["raw_content"], metadata={"source":item["url"]}) 
for item in document_data]
text_splitter = …
```
> Add function get_similar_content_by_query_with_vectorstore. 

- Dockerfile
- gpt_researcher/llm_provider/generic/base.py
- gpt_researcher/memory/embeddings.py
- gpt_researcher/retrievers/searx/searx.py
- gpt_researcher/scraper/arxiv/arxiv.py
- requirements.txt
In relation to #909 
Searx retriever (searx.py) has been rewritten to conform to the SearXNG API specification. Searx is being discontinued and SearXNG is the successor.
N.B. To work with this retriever, the SearXNG service must be configured to enable the `json` output format. By default, for self-hosting scenarios, only `html` format is enabled in the settings.yml file!
> Searx retriever refactoring

- backend/chat/chat.py
- frontend/nextjs/app/globals.css
- frontend/nextjs/components/InputArea.tsx
- frontend/nextjs/components/Question.tsx
Ready for merge 
- fixed breaking changes 
- pulling nextjs chat settings from config
- polished input box to auto-expand and shrink horizontally
> nextjs chat fix

- docs/docs/gpt-researcher/llms/llms.md
- gpt_researcher/memory/embeddings.py
Expanded list of supported embeddings to 
`openai`, `azure_openai`, `cohere`, `google_vertexai`, `google_genai`, `fireworks`, `ollama`, `together`, `mistralai`, `huggingface`, `nomic` and `voyageai`
In relation to issue #629
> Add embedding providers

- docs/docs/gpt-researcher/llms/llms.md
- gpt_researcher/config/config.py
Fix the issue by explicitly setting the embedding model to "text-embedding-3-large" when using Azure openai
> Azure embedding quota limit

- gpt_researcher/retrievers/google/google.py
There's a bug in Google Search where the max_results value in configs aren't respected. Found the bug and fixed it.
> Fix max_results for Google Search

- gpt_researcher/retrievers/google/google.py
```
File "/home/winston/.local/lib/python3.10/site-packages/gp _researcher/retrievers/google/google.py", line 83, in searc
h
"body": result["snippet"],
KeyError: 'snippet'
Error! : HTTPSConnectionPool(host='zyk.bjhd.gov.cn', port=44
3): Read timed out. (read timeout=4)
```
gpt-researcher crashes if a Google search result doesn't contain a snippet (which happens on errors such as read timeout)
> Fix uncaught exception in Google retrieval

- gpt_researcher/config/config.py
```
-        retriever_env = os.environ.get("RETRIEVER", "tavily")
+        retriever_env = os.environ.get("RETRIEVER", config.get("RETRIEVER", "tavily"))
```
Right now if the retriever isn't set in the headers, it defaults to the environment variable RETRIEVER. If that's not set, it defaults to Tavily.
The problem with this is even if the retriever is set in the config, it's completely ignored.
I had no RETRIEVER environment variable set, but I had retriever set in my configs to Bing, Google, etc.,  and was wondering why I was blowing past all my Tavily API limits...
The current workaround is to manually set the retriever in the headers rather than the config.
> Default to the retriever set in config rather than just tavily

- cli.py
- gpt_researcher/llm_provider/generic/base.py
Without this change AWS Bedrock fails with the following error:
Error in reading JSON, attempting to repair JSON
Error using json_repair: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
File "/Users/xo/gpt-researcher/gpt_researcher/actions/agent_creator.py", line 27, in choose_agent
response = await create_chat_completion(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/xo/gpt-researcher/gpt_researcher/utils/llm.py", line 54, in create_chat_completion
provider = get_llm(llm_provider, model=model, temperature=temperature,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/xo/gpt-researcher/gpt_researcher/utils/llm.py", line 19, in get_llm
return GenericLLMProvider.from_provider(llm_provider, **kwargs) …
> Fix AWS Bedrock invocation; create output folder in cli.py if it doesn't exist

- gpt_researcher/prompts.py
#1026 introduced a TypeError when generating subtopic reports due to a missing `language` parameter in the `generate_subtopic_report_prompt` function and causes rearch reports to fail.
Error message:
```python
TypeError: generate_subtopic_report_prompt() got an unexpected keyword argument 'language'
> fix: Add language parameter support to generate_subtopic_report_prompt

- gpt_researcher/prompts.py
```
[ERROR] 2024-12-20 07:13:06 - Error in _get_report
Exception details: generate_custom_report_prompt() got an unexpected keyword argument 'language'
Traceback:
Traceback (most recent call last):
File "ask_gptr.py", line 50, in _get_report
report = await researcher.write_report()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "gpt-researcher/gpt_researcher/agent.py", line 104, in write_report
return await self.report_generator.write_report(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "gpt-researcher/gpt_researcher/skills/writer.py", line 76, in write_report
report = await generate_report(**report_params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "gpt-researcher/gpt_researcher/actions/report_generation.py", line 232, in generate_report
content = f"{generate_prompt(query, context, …
```
> Fix generate_custom_report_prompt language bug

- docs/docs/gpt-researcher/gptr/config.md
- gpt_researcher/actions/query_processing.py
- gpt_researcher/config/variables/base.py
- gpt_researcher/config/variables/default.py
Fix for https://github.com/assafelovic/gpt-researcher/issues/1022
New config variable `smart_token_limit` defaults to 4000 to fix ValidationError thrown by ChatAnthropic when `max_tokens=none`, replacing it with `max_tokens=4000`.
> Introduce strategic_token_limit to fix Anthropic bug

- gpt_researcher/retrievers/google/google.py
Google retriever silently fails to pull the links from the search API with error responses, i.e. 429. It took quite some time to understand where the failure happens because the UI just kept generating content without actually finding anything using the API. This PR to makes sure unexpected response gets logged thus making it easier to debug the running server.
> Prints unexpected Google retriever search API response

- docs/docs/gpt-researcher/frontend/logs.md
- docs/sidebars.js
- docs/yarn.lock
- frontend/nextjs/components/ResearchBlocks/AccessReport.tsx
- frontend/nextjs/components/Settings/ChatBox.tsx
- Added a "Download Log" button to the research report interface that allows users to access detailed logs of the research process. 
- Created documentation with log file explanations
> Logs handler improvements

- backend/server/server.py
- frontend/nextjs/components/ResearchBlocks/AccessReport.tsx
- frontend/nextjs/components/Settings/ChatBox.tsx
Fixed: The code assumes data.output always contains pdf, docx, and json properties without validating their existence. 
Fixed: The code unconditionally prepends 'outputs/' to accessData paths without first checking if they already start with 'outputs/', potentially causing redundant path prefixes. 
Reverted: The "Download Logs" JSON link is now always rendered for all report types, regardless of the previous condition. reverted to conditional and will only display if report type is chatBoxSettings.report_type === 'research_report'
> Bug fixes to unified logs

- gpt_researcher/scraper/__init__.py
- gpt_researcher/scraper/scraper.py
- gpt_researcher/scraper/tavily_extract/tavily_extract.py
Adding Tavily extract as an available scraper. The scraper was added as an additional folder in `gpt_researcher/scraper/`. Tavily extract requires the tavily-python package which is not currently in the requirements.txt, ` _check_pkg()` function was added to `gpt_researcher/scraper/scraper.py ` to dynamically install the package if the scraper is invoked.
> Adding Tavily extract

- gpt_researcher/actions/report_generation.py
Gemini doesn't support role=system.
When `"SMART_LLM": "google_vertexai:gemini-1.5-flash-002"` for example, the current report generation fails with "Error in generate_report".
This fix adds a fallback. It first attempts the original chat completion:
```
messages=[                                                                              
{"role": "system", "content": f"{agent_role_prompt}"},                              
{"role": "user", "content": content},                                               
],
```
Upon failure, it retries with this new chat completion:
```
messages=[                                                                          
{"role": "user", "content": f"{agent_role_prompt}\n\n{content}"},               
],
```
This results in a successful report …
> Fix Gemini bug when system role is provided

- backend/server/server.py
- docs/docs/gpt-researcher/llms/llms.md
- gpt_researcher/llm_provider/generic/base.py
This change adds `deepseek:deepseek-chat`, which is the latest DeepSeek-V3 model (released December 26, 2024).
DeepSeek doesn't have its own LangChain, so official DeepSeek documentation suggests using OpenAI's LangChain (https://api-docs.deepseek.com/faq), which this change implements.
Confirmed working with `FAST_LLM="deepseek:deepseek-chat"`, `SMART_LLM="deepseek:deepseek-chat"`, and `STRATEGIC_LLM="deepseek:deepseek-chat"` when `DEEPSEEK_API_KEY` system variable is set.
> Add DeepSeek to SUPPORTED_PROVIDERS

- gpt_researcher/prompts.py
This PR resolves the `TypeError` caused by passing an unexpected keyword argument `language` to the `generate_resource_report_prompt` function. The fix includes:
1. **Adding `language` as a parameter to the `generate_resource_report_prompt` function.**
2. **Ensuring compatibility in all calls to this function.**
Added `language` as a parameter to align with its usage in `generate_report`.
**Old Function Signature:**
```python
def generate_resource_report_prompt(
question, context, report_source: str, report_format="apa", tone=None, total_words=1000
):
```
To reproduce the error:
1. Run the `gpt-researcher` application.
2. Select **"Resource Report"** when asked, *"What type of report would you like me to generate?"*
3. The application throws the following `TypeError`:
```plaintext …
```
> add parameter to fix resource execution

- docs/docs/gpt-researcher/llms/llms.md
- gpt_researcher/llm_provider/generic/base.py
Add Litellm to supported providers in GenericLLMProvider.
Using Litellm has the following advantages:
Call 100+ LLMs using the OpenAI Input/Output Format
https://docs.litellm.ai/
> Add Litellm to supported providers in GenericLLMProvider

- gpt_researcher/agent.py
- gpt_researcher/skills/researcher.py
The report_source parameter was being incorrectly overridden by the config  default value due to Python's 'or' operator behavior with truthy values.  Changed the logic to explicitly check for the passed parameter first before  falling back to config values.
> preserve user-specified report source instead of config default

- multi_agents/agents/utils/file_formats.py
Use os.path to make the CSS file path relative to the current Python file's
location instead of using a hardcoded path. This makes the code more robust
and portable.
Fixes #1008
> multi_agent: update CSS path to be relative to current file

- backend/server/websocket_manager.py
- docker-compose.yml
- main.py
- tests/test_logging_output.py
1. Event logging fixed to populate JSON log (appears to have been a regression recently re-introduced. 
2. Added tests to make sure event logging creates a requesite file. 
3. Changed way docker logs font issues from WeasyPrint to be less verbose.
> Logging update. Fixed regression and update to Docker log handling. 

- gpt_researcher/actions/report_generation.py
- gpt_researcher/prompts.py
First, thank you for considering my contribution to the GPT Researcher project. This PR addresses the issue [#1100](https://github.com/assafelovic/gpt-researcher/issues/1100#issue-2828944245) where the Introduction and Conclusion sections of research reports do not respect the LANGUAGE configuration setting.
When `LANGUAGE` is set to a non-English value in the configuration (e.g., "japanese"), the Introduction and Conclusion sections remain in English while the rest of the report is generated in the configured language. This creates inconsistency in the report output.
- Modified report generation to pass language configuration to Introduction and Conclusion generation prompts
- Ensures consistent language usage throughout the entire report
- Maintains existing config system behavior while …
> fix(#1100): apply language config to Introduction and Conclusion sections

- gpt_researcher/prompts.py
when run cli script
```
python cli.py "story protocol" --report_type outline_report
```
it throws error:
```
File "/home/gpt-researcher/gpt_researcher/actions/report_generation.py", line 237, in generate_report
content = f"{generate_prompt(query, context, report_source, report_format=cfg.report_format, tone=tone, total_words=cfg.total_words, language=cfg.language)}"
TypeError: generate_outline_report_prompt() got an unexpected keyword argument 'language'
```
I found that because generate_outline_report_prompt does not have language param
> fix: add language param to generate_outline_report_prompt

- docs/docs/gpt-researcher/llms/llms.md
This is a bit of a flyby PR, but hopefully this saved someone 5 minutes.
> Fixed broken configuration link in llms.md

- gpt_researcher/scraper/scraper.py
Enhance Scraper Logging and Title Handling
This PR improves the scraping functionality in two ways:
1. Adds detailed logging for scraper operations to help with debugging and monitoring
2. Fixes inconsistent title handling in the scraper return values
- Added structured logging in `extract_data_from_url` method including:
- Scraper type being used
- Page title
- Content length
- Number of images found
- URL being processed
- Modified error cases to return the actual scraped title instead of empty string
- Added warning log for short/empty content cases
The changes can be tested by:
1. Running a research task with various URLs
2. Checking the logs in:
- Console output
- `logs/app.log`
- ~~Task JSON output~~
- Web UI agent output
3. Verifying that titles are preserved even when content is …
> feat: enhance scraper logging and title handling

- gpt_researcher/scraper/browser/browser.py
`soup.find_all(tags)` returns nested tags even if the text blocks are already extracted from their parent tag. This lead to large amount of duplicate text blocks.
prefer `soup.get_text(strip=True, separator="\n")` for a much smaller result size.
> Fix scraper browser returns duplicate texts

- gpt_researcher/actions/query_processing.py
- gpt_researcher/utils/llm.py
As discussed in issue #1098, this pull request adds support for the o3-mini model without impacting users of other models.
o3-mini is much faster (higher latency but much higher throughput) and cheaper than 4o and previous o1 models. Adding support for it allows for faster more complete research at similar prices.
> Adds support for o3-mini

- gpt_researcher/actions/agent_creator.py
This enhances logging for incorrect json format produced by llm.
llm frequently produce slightly incorrect json. Logging `⚠️ Error in reading JSON, attempting to repair JSON` when there is a slight inaccuracy in the json reponse is unnecessary when it can be fixed with `json_repair`.
This PR removes the unnecessary logging and adds more detailed logging when `json_repair` fails.
> Enhanced incorrect json format handling at agent_creator.py

- gpt_researcher/scraper/arxiv/arxiv.py
On setting RETRIEVER=arxiv, an error comes and content is not retrieved.
Reference for fix: https://python.langchain.com/docs/integrations/retrievers/arxiv/#usage
> Fix: ArxivScraper causing error when scraping the link.

- docs/docs/gpt-researcher/gptr/scraping.md
- gpt_researcher/scraper/__init__.py
- gpt_researcher/scraper/firecrawl/firecrawl.py
- gpt_researcher/scraper/scraper.py
- pyproject.toml
Add support for FireCrawl scaper for page content and page title.
It should be support self host or official service from FireCrawl by set enviroment variables `FIRECRAWL_SERVER_URL` and `FIRECRAWL_API_KEY`.
And set `SCRAPER=firecrawl` to use FireCrawl scaper.
Already tested with selft hosted FireCrawl.
> Add FireCrawl scaper

- gpt_researcher/skills/deep_research.py
I changed the combined_query in the run() method of DeepRsearchSkill class to solve a bug with backlashes in f-strings that was causing the building of the docker image to fail - now the build work.
> Fix Docker Build Failure: Updated `combined_query` in `DeepRsearchSkill.run()` to Handle Backslashes in F-Strings

- gpt_researcher/utils/llm.py
Resolved issue #1185 by checking for the base url in the environment variables and adding it to the arguments sent to llm provider.
> Added support for base_url param in create_chat_completions for OpenAI Provider

- requirements.txt
This PR adds the missing langgraph module to requirements.txt. The absence of this dependency caused issues when setting up the project in a new environment.
Changes:
Added langgraph to requirements.txt
This update ensures that all required dependencies are properly installed when running pip install -r requirements.txt.
> fix: Add missing langgraph module to requirements.txt

- gpt_researcher/actions/agent_creator.py
- gpt_researcher/actions/retriever.py
- gpt_researcher/agent.py
- gpt_researcher/prompts.py
- gpt_researcher/skills/browser.py
- gpt_researcher/skills/researcher.py
- gpt_researcher/utils/llm.py
Introduces some non-functional improvements aimed mainly at modernizing the codebase and improving readability, only affecting the part I have come across so far:
- Type annotations: Updated type annotations to use the built-in `list` and `dict` types instead of `List` and `Dict` from the typing module, and replaced `Optional` with the union type (`| None`) since Python 3.11+ is required.
- Code Cleanup: Removed unused imports and mutable default arguments from function signatures.
- Documentation Improvements: Refined duck typing hints and updated docstrings.
- Formatting Fixes: Applied minor formatting improvements.
> Refactor: typing cleanup

- gpt_researcher/prompts.py
Other reports already support multiple languages, but it seems that the Resource Report was missing this feature. This PR adds multi-language support to ensure consistency
> Add language requirement to resource report prompt

- backend/server/server_utils.py
- frontend/nextjs/app/page.tsx
- frontend/scripts.js
a long running task might block the web socket from handling new incoming messages, and thus the messages will be accumulated in the queue. eventually the queue can be full and lead to unexpected behavior.
This fix puts long running tasks to background and discard any new request except for the ping message.
> fix: unblock web socket message queue

- gpt_researcher/actions/web_scraping.py
- gpt_researcher/scraper/utils.py
- gpt_researcher/skills/browser.py
I found a strange thing in the current image filtering logic, that seems to ignore images with the highest "relevance score" 4, and also performs unnecessary steps.
Maybe I'm missing something here, but I wouldn't expect this behavior so implemented a fix, as well as some type hinting clean up in the affected files.
> Fix: image relevance filtering

- pyproject.toml
- tests/test_logging_output.py
Internal package’s WebSocket implementation, if bool is not defined, Python falls back to calling len. In our case, len returns the length of self.scope, which has been updated to always include at least the key "type": "websocket" to match the internal package implementation.
Additionally, for test stability and to verify the existence of the TestWebSocket instance, I have overridden bool in TestWebSocket class.
> fix: resolve failing test in tests/test_logging_output.py

- pyproject.toml
This PR updates the Python version specification in pyproject.toml from ">=3.11" to ">=3.11, <3.13" to resolve dependency conflicts with the unstructured package. The unstructured package requires Python versions <3.13, but our previous version constraint allowed Python 3.13 and above, which caused conflicts during dependency resolution.
```
poetry install
Updating dependencies
Resolving dependencies... (1.3s)
The current project's supported Python range (>=3.11) is not compatible with some of the required packages Python requirement:
- unstructured requires Python <3.13,>=3.9.0, so it will not be satisfied for Python >=3.13
- unstructured requires Python <3.13,>=3.9.0, so it will not be satisfied for Python >=3.13
...
....
.....
Because no versions of unstructured match >0.13,<0.13.2 || …
```
> fix: restrict Python version range in pyproject.toml

- cli.py
Addresses KeyError: 'deep' resulting from python cli.py.
Adds option for Deep Research in cli.py using ' DeepResearch = "deep" ' from enum.py (line 11).
Executing python cli.py now works as anticipated, including for report_type "deep".
> Fix KeyError: 'deep' in cli.py

- backend/server/server_utils.py
Long queries still make task log file paths too long for Windows to handle (255) which causes frontend app to throw errors and crash research task at the start (tested locally).  Current truncating mechanism doesn't include real length for path to project, it just leaves 10 chars for safety margin
> fix: truncating task file names for long queries

- gpt_researcher/llm_provider/generic/base.py
The generic LLM provider tries to dynamically pip install packages that are not currently available, but the routine that does this does not have subprocess or sys imported, so the code throws at runtime.
Fixes issue: #1251
> Add missing imports

- gpt_researcher/prompts.py
- gpt_researcher/scraper/arxiv/arxiv.py
- gpt_researcher/scraper/pymupdf/pymupdf.py
- Include the published date and author to align with APA-style formatting for the results from the Arxiv scraper.
- Returning the content, image (if any), and title from the PDF scraper to prevent ValueError, retrieving only the first page to minimize embedding costs.
- Adjust prompt, especially detail report prompt for report format to maintain consistency on the final report
> Add published date and author to Arxiv context; adjust PDF scraper return; adjust detail report prompt for consistent formating style

- backend/report_type/basic_report/basic_report.py
- backend/server/server.py
- backend/server/websocket_manager.py
- docs/npm/index.js
Resolving issue https://github.com/assafelovic/gpt-researcher/issues/1232
The server now accepts post requests for generating reports. The execute_in_background flag can be used to wait for the report to finish generating and return the report, or just return the report_id to then fetch the report later using a get request.
The sendMessage function in npm package now accepts useHTTP and execute_in_background params to decide whether to use websockets or HTTP and whether to wait for the report to finish. The npm package also has a getReport function which accepts the report_id and retrieves the report.
> Added post and get http endpoints to server and updated npm package to allow sending http requests

- docs/docs/gpt-researcher/llms/llms.md
- gpt_researcher/llm_provider/generic/base.py
This pull request introduces support for the Openrouter.ai LLM provider.
* [`docs/docs/gpt-researcher/llms/llms.md`](diffhunk://#diff-66e67992fcc7f98a640cf20b6db5746d0563c4ece5fd0ecacdb14c01b7a2bc51R302-R313): Added configuration instructions for using Openrouter.ai, including setting environment variables for API keys, base URL, and model identifiers.
* [`gpt_researcher/llm_provider/generic/base.py`](diffhunk://#diff-566085fd98745d6c73683585cd9225b6b86248ef2f95180cd326be652e765a26L27-R28): Added "openrouter" to the list of supported LLM providers.
* [`gpt_researcher/llm_provider/generic/base.py`](diffhunk://#diff-566085fd98745d6c73683585cd9225b6b86248ef2f95180cd326be652e765a26R164-R182): Implemented the `from_provider` method to support initializing the `ChatOpenAI` model from …
> New provider openrouter.ai added

- gpt_researcher/document/online_document.py
Some sites won't respond to URLs without a User-Agent specified
> Add User-Agent: Mozilla when downloading a file

- multi_agents/agents/publisher.py
When running the multi-agent system, an error occurs in the `PublisherAgent` class when trying to process research data that contains string values instead of dictionaries:
```
AttributeError: 'str' object has no attribute 'items'
```
This happens because the `generate_layout` method assumes all items in `research_data` are dictionaries with an `.items()` method, but sometimes they can be strings.
Modified the `generate_layout` method in `PublisherAgent` to handle both dictionary and string values in the research data:
1. Added type checking with `isinstance(subheader, dict)` to handle different data types
2. Changed from a nested list comprehension to a more explicit loop structure
3. Added proper handling for string values in the research data
4. Added default empty values for …
> Fix AttributeError in PublisherAgent when processing string values

- docs/docs/gpt-researcher/llms/llms.md
Replace `gpt-researcher/gptr/config` with `docs/gpt-researcher/gptr/config`
> Fix broken link in llms.md

- gpt_researcher/llm_provider/generic/base.py
Added `"o4-mini"` to `NO_SUPPORT_TEMPERATURE_MODELS` and `SUPPORT_REASONING_EFFORT_MODELS`.
Without this change, the temperature is incorrectly set for the `o4-mini` model, leading to unexpected LLM behavior.
> Add support for o4-mini model in temperature & reasoning-effort config

- docs/docs/gpt-researcher/llms/llms.md
The previous structure raised the following exception: ValueError: not enough values to unpack (expected 2, got 1)
> EMBEDDING = '<hugginface>:<sentence-transformers/all-MiniLM-L6-v2>'

- docs/docs/gpt-researcher/llms/supported-llms.md
- gpt_researcher/config/config.py
- gpt_researcher/memory/embeddings.py
LLM already works, adds embeddings from GigaChat team.
> feat: Adds support for gigachat embeddings to the gigachat LLM add-on.

- gpt_researcher/agent.py
- gpt_researcher/config/config.py
- gpt_researcher/llm_provider/generic/base.py
This fixes [the issue](https://github.com/assafelovic/gpt-researcher/issues/1360) I raised earlier. After going through the codebase, it seemed neater to pop the verbose property on `Config` and populate it. This does create a potential bug where somebody could set `LLM_KWARGS.verbose` in their config file and then it could be overridden by the parameter passed to an instance of the GPT researcher object, but I feel like this gives more granular control than always deferring to the config file.
> Respect my verbosity! 

- backend/report_type/deep_research/example.py
In Python 3.11 and earlier, f-strings are not allowed to contain backslashes.
so in backend/report_type/deep_research/example.py, it raise error when python  = 3.11  
```python
combined_query = f"""
Initial Query: {self.query}
Follow-up Questions and Answers:
{' '.join([f'Q: {q}\nA: {a}' for q, a in zip(follow_up_questions, answers)])}   #here
"""
```
> fix python3.11 f-string cannot have backslash

- multi_agents/agents/editor.py
- multi_agents/agents/orchestrator.py
The third argument of [ResearchAgent](https://github.com/assafelovic/gpt-researcher/blob/f84e6130b2af47b01fec3cee9ec2dcdb00169a0e/multi_agents/agents/researcher.py#L7) has to be `tone`, but the instantiation of it within EditorAgent [does not include that](https://github.com/assafelovic/gpt-researcher/blob/f84e6130b2af47b01fec3cee9ec2dcdb00169a0e/multi_agents/agents/editor.py#L120). So, I add an instance variable of tone to EditorAgent and the tone variable as the third argument of ResearchAgent for initialization.
> bugfix. third argument of ResearchAgent has to be tone

- gpt_researcher/scraper/pymupdf/pymupdf.py
Hi, just a quick fix for two bugs in `PyMuPDFScraper`:
1. In case of problems, there were no `return` statements in the except blocks, that caused the function to implicitly return `None`, and that errors out [in here](https://github.com/assafelovic/gpt-researcher/blob/master/gpt_researcher/scraper/scraper.py#L103C1-L113C22), because `None` can not be unpacked to three variables. I added returning of empty strings/lists, as is done in other scraper classes as well.
2. It was typed to return `str`, but actually it returns `tuple[str, list[str], str]`
> Fix return statements in PyMuPDFScraper

- gpt_researcher/actions/agent_creator.py
- gpt_researcher/actions/query_processing.py
- gpt_researcher/actions/report_generation.py
- gpt_researcher/agent.py
- gpt_researcher/context/compression.py
- gpt_researcher/llm_provider/generic/base.py
- gpt_researcher/skills/context_manager.py
- gpt_researcher/skills/researcher.py
- gpt_researcher/skills/writer.py
- gpt_researcher/utils/llm.py
This PR exposes `**kwargs` throughout the codebase, allowing seamless integration with LangChain’s extended ecosystem including support for callback handlers such as **Langfuse**, tracing tools, and custom monitoring utilities.
With this change, you can now pass in LangChain-native arguments directly through the config, enabling much richer observability and control over the research process.
**Related Issues:**  
- Closes #1129 
- Closes #1298 
- **Unlocks integrations**: Easily connect tools like Langfuse using their official `CallbackHandler`
- **Future-proof**: Supports upcoming LangChain features without further changes
- **Better tracing & debugging**: Full visibility into model steps and decisions
```python
from dotenv import load_dotenv
from langfuse.callback import …
```
> Expose **kwargs throughout core modules to unlock LangChain integrations

- backend/server/server_utils.py
Description:
Fixes #1418
This issue arises because the file name length is calculated in bytes, while the sanitize_filename function calculates it by character count.
For English, where each character typically corresponds to a single byte, this wasn't an issue. However, Chinese characters are multi-byte, leading to incorrect length calculations.
This patch is a refinement of the solution provided by Claude-3.7-Sonnet. Additionally, I've removed newline, carriage return, and whitespace characters from the filename, as I believe they can easily cause other problems.
> Fix #1418: OSError: [Errno 36] File name too long with long Chinese prompt

- gpt_researcher/utils/llm.py
**Problem Description**
When generating subtopic reports for the detailed report, the following error was encountered:
`Exception in parsing subtopics : Connection error`
As a result, neither the table of contents nor the subtopic reports are generated in the final output report.
**Solution**
- Changed the blocking `invoke` call to the asynchronous `ainvoke` to avoid blocking the event loop.
- Added additional logging for improved debugging and traceability.
> Fix zero subtopic error

- gpt_researcher/retrievers/exa/exa.py
The query domains were ignored by the exa retriever. This commit makes it follow the limitation.
> fix: make exa retriever respect query domains

- gpt_researcher/skills/context_manager.py
**Describe the bug**
The vectorstore_filter parameter passed in GPTResearcher class is not passed the VectorstoreCompressor and VectorStoreWrapper class while conduct research.
**To Reproduce**
Steps to reproduce the behavior:
In `gptresearcher/context/compression.py -> VectorStoreCompressor` Make this change to async_get_context
```
async def async_get_context(self, query, max_results=5, cost_callback=None):
print(f"DEBUG: VectorstoreCompressor.async_get_context using filter: {self.filter}")
results = await self.vector_store.asimilarity_search(query=query, k=max_results, filter=self.filter)
print(f"DEBUG: VectorstoreCompressor.async_get_context raw results (first 2 metadata): {[r.metadata for r in results[:2]]}")
return self.prompt_family.pretty_print_docs(results)
```
In …
> bug_fix: vectorstore_filter not passed

- frontend/styles.css
-Point the landing background to an existing asset to remove a missing-file 404 in the browser console.
- Changes:
- `frontend/styles.css`: Use `./static/gptr-logo.png` instead of the missing
`powerful_wizard.png`.
- Why: Cleans up a persistent 404 on initial load and avoids an unnecessary network request.
- Testing:
- Load landing page and confirm no 404 in Network/Console.
- Verify background still renders.
- Risk: Low — CSS path change to an existing file.
> fix(frontend): use existing gptr-logo.png for background to stop 404
