client/scripts.js

Replaced hardcoded localhost with dynamic ws url generation
Fixes: https://github.com/assafelovic/gpt-researcher/issues/30

Support non localhost setups

---

CONTRIBUTING.md
README.md

Contribution

---

client/index.html
client/scripts.js
client/styles.css

**Update HTML file**
**Commit Description:**
- Added initial HTML structure to index.html.
- Prepared the layout for the landing section.
- Created form elements for user input and agent selection.
- Set up the containers for agent responses and research reports.
---
**Update CSS file**
**Commit Description:**
- Styled the landing section with a gradient background animation.
- Applied consistent font family and color scheme.
- Added hover and focus styles for input and select elements.
- Styled primary and secondary buttons with gradient backgrounds.
- Implemented responsive design for the container and agent response sections.
---
**Update JavaScript file**
**Commit Description:**
- Implemented the `startResearch` function to initiate the research process.
- Listened to WebSocket events …

Commit Message: Update HTML file,Update CSS file,Update JavaScript file

---

actions/web_scrape.py
agent/llm_utils.py
agent/research_agent.py
agent/run.py
client/index.html
main.py

Helps choosing agents automatically according to users' input using openAI's gpt functions

Auto agent choosing

---

client/index.html
main.py

Removed agent selection so it will be only automated for reduced friction and higher content quality

removed selection of agents

---

README.md
agent/llm_utils.py
agent/prompts.py
config/config.py

Moved provider var to config file for easier llm integration setup.

Langchain adapter config

---

Dockerfile

Adding additional command for app directory root ownership due to issues with windows setup

added permissions ownership for docker

---

actions/web_scrape.py
requirements.txt

Closes #171 since the correct version is always installed and selected if unavailable.

Added module to autoupgrade and select the proper Chromedriver version

---

client/index.html
client/scripts.js

This isn't the prettiest solution, but it works.
Also commented out some JS in the index.html which was causing an error because that element doesn't exist.
Until the app is moved to a framework, this should do the trick.  Closes #180

Fixes the UX issue of download buttons showing before the report is done

---

README.md
actions/web_scrape.py
actions/web_search.py
config/config.py
requirements.txt

first, i want to say thank you so much. this is an amazing project!
i added google api and google serp option to front and back end along with .env and updated docker-compose file

adding google api and google serp api

---

actions/web_search.py

The google updated serp api version, the old one will trigger problems.

Fix Google SerpAPI bug (Update the SerpAPI to Latest Version)

---

setup.py

setup.py for the pip package, played with it and saw that it's working :).
if you want to test it on your machine run:
`pip install wheel`
`python setup.py bdist_wheel sdist`
`pip install .` -> in order to get it installed locally
when you'll want to push it to PyPi you'll have to install twine
(You might have install requirements.txt too cause the project includes the fastapi part and it cannot be ignored, but when users will install it you won't have to do it).
example usage:
```python
from build.lib.master import GPTResearcher
import asyncio
async def get_report(query: str, report_type: str) -> str:
researcher = GPTResearcher(query, report_type)
report = await researcher.run()
return report
if __name__ == "__main__":
query = "where should i eat pizza in paris?"
report_type = …
```

added setup.py for the pip package

---

gpt_researcher/master/functions.py
gpt_researcher/retrievers/__init__.py
gpt_researcher/retrievers/bing/bing.py

Adding BingSearch Bing Web Search API retriever. Requires ["BING_API_KEY"] env variable set to work.

Add Bing Search Retriever

---

gpt_researcher/scraper/__init__.py
gpt_researcher/scraper/arxiv/arxiv.py
gpt_researcher/scraper/beautiful_soup/beautiful_soup.py
gpt_researcher/scraper/newspaper/newspaper.py
gpt_researcher/scraper/pymupdf/pymupdf.py
gpt_researcher/scraper/scraper.py
gpt_researcher/scraper/web_base_loader/web_base_loader.py

Also included a new scraper from langchain_community: WebBaseLoader. WebBaseLoader works quite fast.
Support for more such loaders can be integrated in the future with a similar interface.

Refactored each scraper into its own folder.

---

docs/docs/faq.md
docs/docs/tavily-api/introduction.md
docs/docs/tavily-api/rest_api.md

Noticed an inconsequential spelling mistake in a file. Searched across all files and found three occurrences in total.

doc: correct spelling to 'proprietary'

---

gpt_researcher/master/prompts.py

Modified report prompts to ensure url links in the references section are hyperlinked!

Modified prompts to introduce hyperlinked reference urls

---

backend/server.py
backend/utils.py
docs/docs/examples/examples.ipynb
docs/docs/examples/examples.md
docs/docs/tavily-api/langchain.md
frontend/index.html
frontend/scripts.js
gpt_researcher/master/agent.py
gpt_researcher/memory/embeddings.py
gpt_researcher/retrievers/searx/searx.py
gpt_researcher/utils/llm.py
poetry.lock
pyproject.toml
requirements.txt

1. Speed up by using async sub-query processing
2. Support for saving report in docx format
3. Support for python 3.10
4. Updated imports as per latest langchain standards
5. Replaced deprecated lc_openai in favour of more modern ChatOpenAI langchain approaches

Optimizations and features updates

---

config.json
docs/docs/gpt-researcher/config.md
gpt_researcher/config/config.py
gpt_researcher/llm_provider/__init__.py
gpt_researcher/llm_provider/google/google.py
gpt_researcher/llm_provider/openai/openai.py
gpt_researcher/utils/llm.py
poetry.lock
pyproject.toml
requirements.txt

1. Refactored each provider into its own folder.
2. Support for GEMINI !
3. Using config variable "llm_providers" to select provider.

New folder structure and interface for providers + GEMINI

---

docker-compose.yml
gpt_researcher/config/config.py
gpt_researcher/llm_provider/__init__.py
gpt_researcher/llm_provider/azureopenai/azureopenai.py
gpt_researcher/memory/embeddings.py
gpt_researcher/utils/llm.py

Adding native Azure OpenAI LLM provider support including the embedding models.
Env. variables required for support to work:
AZURE_OPENAI_ENDPOINT="INSERT_ENDPOINT_URL e.g. https://xxxx.openai.azure.com/"
AZURE_OPENAI_API_KEY="INSERT_AZURE_OPENAI_ENDPOINT_KEY"
OPENAI_API_VERSION="INSERT_AZUREOPENAI_API_VERSION_NO e. 2023-08-01-preview"
OPENAI_API_TYPE="azure"
Note also new entry in config.py to specify the Azure OpenAI embedding model name:
self.azure_embedding_model = os.getenv('AZURE_EMBEDDING_MODEL', "INSERT_EMBEDDIGN_MODEL_DEPLOYMENT_NAME")

Adding Azure OpenAI LLM Provider Support "azureopenai"

---

gpt_researcher/llm_provider/azureopenai/azureopenai.py
gpt_researcher/utils/llm.py

Hotfix for #422 & #427  Detailed report azureopenai support plus azureopenai LLM settings documentation improvement.

Hotfix for #422 & # 427 : LLM provider = azureopenai when using detailed report mode

---

Dockerfile
requirements.txt

added required websocket library to requirements.txt and added --fix-missing flag to dockerfile to fix missing dependencies if encountered during installation.

Docker fixes

---

docs/docs/gpt-researcher/llms.md

Added Instructions for Groq

---

gpt_researcher/llm_provider/together/together.py

Read the correct variable name, "MISTRAL_API_KEY" to "TOGETHER_API_KEY"

Read the correct variable name in together.py

---

gpt_researcher/config/config.py

-fix: duplicated and wrong self.fast_token_limit

fix: similarity_threshold config

---

gpt_researcher/master/actions.py

based on comment from @mangiucugna, json_repair author

update on using json_repair from the author of json_repair, thanks!

---

gpt_researcher/master/actions.py

Reason: When I was testing the limits of this project I noticed that passing off any instructions through the agent as a query broke the choose_agent function as the response contained non-JSON formatted text.
Suggestion: I have added two new async functions to handle different JSON errors using the already imported json_repair library and regex as a last resort.
Importance: This contribution is important because it makes the user experience remain relevant to the research task even when the user (who might not be technically adept) decides to pass instructions in the prompt.

Implement more graceful JSON handling on choose_agent in master/actions.py

---

gpt_researcher/master/actions.py
gpt_researcher/retrievers/__init__.py
gpt_researcher/retrievers/exa/exa.py

Description:
The imports for the retrievers module have been updated to include the new `ExaSearch` class. This enhancement adds a new retriever capability using the **Exa API**, enabling more robust and flexible search functionalities.
Key Changes:
- Added `ExaSearch` class to the retrievers module.
- Updated import statements to integrate `ExaSearch`.
- Provided necessary documentation for `ExaSearch` usage.
Please review the changes and let me know if any adjustments are needed.

chore: Update retrievers imports

---

gpt_researcher/master/agent.py

Pull request to address an issue where references from prior runs might be incorporated into following runs.
Added these two lines and a comment 'conduct_research()':
async def conduct_research(self):
"""
Runs the GPT Researcher to conduct research
"""
self.visited_urls.clear()
self.source_urls = []

Correct issue #623 where references from proir runs may remain.

---

.gitignore
backend/report_type/basic_report/basic_report.py
backend/report_type/detailed_report/detailed_report.py
backend/server.py
backend/websocket_manager.py
frontend/index.html
frontend/scripts.js
gpt_researcher/master/actions.py
gpt_researcher/master/agent.py
gpt_researcher/master/prompts.py
gpt_researcher/utils/enum.py

- Updated .gitignore to include necessary changes.
- Modified basic_report.py and detailed_report.py in backend/report_type to incorporate tone selection.
- Modified server.py and websocket_manager.py in backend to handle tone input.
- Modified frontend/index.html and scripts.js to provide tone selection option to users.
- Modified actions.py, agent.py, and prompts.py to process and generate reports based on selected tone.
- Modified enum.py in utils to include tone options.
This update allows users to select the tone of the research report, improving the customization and user experience of the research reports generated by gpt-researcher.
The user can now choose the tone of the article on the frontend from the following options:
- Objective: Impartial and unbiased presentation of facts …

Add tone selection feature to research report

---

gpt_researcher/master/prompts.py

This pull request addresses an issue with the generate_report_prompt function, where the tone parameter was not accepted, leading to a TypeError. The following changes have been made:
1. Function Update: Modified the generate_report_prompt function to accept the tone parameter. This involved updating the function signature and adding logic to handle the tone parameter if provided.
2. Code Refactoring: Updated the relevant function calls to include the tone parameter where necessary.
3. Documentation: Added comments and documentation to ensure the changes are clear and maintainable.
4. Testing: Ran tests to ensure that the changes do not break existing functionality and that the new parameter is handled correctly.
These changes should resolve the TypeError and allow the function to …

Fixed the issue with the generate_report_prompt function to accept the tone parameter

---

gpt_researcher/master/agent.py
gpt_researcher/master/prompts.py

The constructor of GPTResearcher was unable to pick up the default tone when none was provided, causing an issue when calling GPTResearcher without specifying a tone. This change will fix this bug.

Fix tone issue related to the default constructor of GPTResearcher

---

multi_agents/agents/master.py
multi_agents/agents/utils/utils.py
multi_agents/utils/utils.py

**Description:**
This PR introduces a function to sanitize directory names to ensure compatibility with Windows operating systems. The primary change is in the ChiefEditorAgent class, where the directory name for storing output files is now sanitized to replace invalid characters.
**Changes Made:**
- Added sanitize_filename function to replace invalid characters in directory names.
- Updated ChiefEditorAgent to use the sanitize_filename function when creating output directories.
**Background:**
The project was functioning correctly on Linux but encountered errors on Windows due to invalid characters in directory names (e.g., ?, *, |). This update addresses those issues by sanitizing the directory names, making the project cross-platform compatible.

Sanitize Directory Names to Ensure Compatibility with Windows

---

gpt_researcher/retrievers/tavily/tavily_search.py

This addressed the issue pointed out in #678. I tested it locally using Tavily search.

Make header an optional argument in TavilyClient

---

README-ja_JP.md
README-zh_CN.md
README.md

I created Japanese translated README.

docs: add Japanese README

---

backend/server.py
backend/websocket_manager.py
frontend/index.html
frontend/scripts.js
frontend/styles.css
gpt_researcher/master/agent.py
gpt_researcher/utils/enum.py
multi_agents/frontend/components/Search.tsx
multi_agents/frontend/components/Settings/FileUpload.js

This pull request introduces several enhancements to the FileUpload component. Below are the detailed changes:
Uploaded Files List:
-     Styled the list of uploaded files for a cleaner, more organized presentation.
-     Used Tailwind CSS classes to ensure consistent design and spacing across the component.
'n' to &apos;n&apos; because typescript error 
Added preventDefault in the delete button onClick event to prevent the modal from closing.

Enhance File Upload Component with Improved UI and Delete Functionality

---

backend/server.py
backend/websocket_manager.py
frontend/index.html
frontend/scripts.js
frontend/styles.css
gpt_researcher/master/agent.py
gpt_researcher/utils/enum.py
multi_agents/frontend/components/Search.tsx

1. In this way, source_urls to be researched can be added and research is done only through these source_urls
2. Frontend changes have been applied. If report_source is selected as sources, the input field opens and source_urls can be added.
On multi agent side 
report_type and report_source have been replaced with names from the parameter as reportType and reportSource

Source url research feature added and Fixes report_source and report_type value on multi agents side

---

.env.example
gpt_researcher/master/actions.py
gpt_researcher/retrievers/__init__.py
gpt_researcher/retrievers/pubmed_central/pubmed_central.py

This PR introduces the PubMed Central retriever to our list of available retrievers, enabling access to NCBI (National Center for Biotechnology Information) services, including PubMed Central and other NCBI databases. 
The following files have been updated:
- `gpt_researcher/retrievers/__init__.py`
- `gpt_researcher/master/actions.py`
The following files have been added:
- `gpt_researcher/retrievers/pubmed_central/__init__.py`
- `gpt_researcher/retrievers/pubmed_central/pubmed_central.py`
Additionally, the `.env.example` file now includes a new environment variable, `NCBI_API_KEY`, necessary for accessing the NCBI services.

Add PubMed Central retriever

---

backend/report_type/detailed_report/detailed_report.py
frontend/styles.css
gpt_researcher/context/compression.py
gpt_researcher/context/retriever.py
gpt_researcher/master/actions.py
gpt_researcher/master/agent.py
gpt_researcher/master/prompts.py
multi_agents/task.json

In the current `DetailedReport`, it is easy to get redundant content across different subtopics. This is because only `existing_headers` are used to ask the LLM to prevent generating duplicate subsections. In #548, I mentioned this problem and had some discussions to plan modifications to fix it.
In my solution, the whole process can be described in the following steps:
For each subtopic report generation:
1. Pass the `global_written_contents`, which are written by previous subtopic reports, into the current subtopic researcher.
2. Based on the conducted context, generate draft section titles for later retrieval.
3. Use the current subtopic task + draft section titles to retrieve relevant written content from `global_written_contents`.
4. Write new subtopics based on the conducted context …

Feature: Reducing redundancy problems in Detailed Reports

---

gpt_researcher/retrievers/__init__.py

fix unimport ExaSearch when use Exa

fix unimport ExaSearch when use Exa

---

docs/docs/gpt-researcher/langgraph.md
gpt_researcher/config/config.py
gpt_researcher/master/agent.py
multi_agents/README.md
multi_agents/agents/__init__.py
multi_agents/agents/editor.py
multi_agents/agents/human.py
multi_agents/agents/master.py
multi_agents/main.py
multi_agents/memory/research.py
multi_agents/requirements.txt
multi_agents/task.json

Adding ability to get feedback from humans in the loop of planning the research strategy

Multi Agents - Human in the Loop

---

gpt_researcher/master/actions.py
gpt_researcher/master/prompts.py

Removed unnecessary functions and added the tone parameter to generate the report to address this [issue](https://github.com/assafelovic/gpt-researcher/issues/719).

chore: Update generate_report function to include tone parameter

---

docs/docs/gpt-researcher/llms.md
gpt_researcher/config/config.py
main.py
requirements.txt

I just ran into this problem: by default GPT-R assumes I have a GPT-4o-mini at hand, which we don't, because Microsoft doesn't offer it yet in Europe.
Digging a bit into the code I changed the following:
1. config.py -- allow for setting a default model
2. llms.md -- documented the env vars that need to be set
3. base.py -- let the .env file be loaded before the app is imported

Improved azure openai config

---

requirements.txt

Updated the requirements.txt to refer to ```loguru``` package instead of  ```logurun```

BugFix:  Version 0.9.1 cannot be installed #806

---

cli.py
docs/docs/gpt-researcher/tailored-research.md
examples/sample_report.py
examples/sample_sources_only.py
gpt_researcher/context/compression.py
gpt_researcher/master/agent.py
gpt_researcher/utils/enum.py

* Removed CLI hint for detailed_report
* Fixed bug with static sources being ignored
* Refactored core functions

Bug fixes and improvements

---

README-ja_JP.md
README-ko_KR.md
README-zh_CN.md
README.md

I've been truly impressed by the work you've done on this project, and to make it more accessible to Korean-speaking users, I have translated the README file into Korean. I believe this will help broaden the project's reach and make it easier for Korean developers to understand and contribute.
Please let me know if there are any changes or improvements you'd like me to make.
Thanks.

[Document] Add korean translation

---

docs/docs/gpt-researcher/config.md

**Enhancements:**
- Added a more concrete example of a non-OpenAI model configuration.
- Included a link to LangChain for further information on model parameters, as each LLM provider requires different environment keys.

added an example on a custom configuration e.g. Azure

---

README-ja_JP.md
README-ko_KR.md
README-zh_CN.md
README.md
docs/docs/gpt-researcher/getting-started/getting-started.md
docs/docs/gpt-researcher/getting-started/introduction.md
docs/docs/gpt-researcher/gptr/config.md
gpt_researcher/README.md

more docs link fixes - linked to folder instead of files in these places

✅: Docs fixes

---

frontend/nextjs/app/page.tsx
frontend/nextjs/components/Settings/FileUpload.js

This pull request addresses several issues and implements optimizations in the FileUpload component. The changes include resolving React Hook warnings, improving performance, and ensuring proper dependency management.
- Wrapped the `fetchFiles` function in a `useCallback` Hook.
- Added `host` to the dependency array of `useCallback`.
- Updated the `useEffect` dependency array to include `fetchFiles`.
- Created a `uniqueKey` variable using the index to ensure unique keys for each iterated element.
- Added the `key` prop to the div element in the iterator.
```jsx
// Before
import React, { useEffect, useState } from 'react';
const FileUpload = () => {
const [files, setFiles] = useState([]);
const host = getHost();
const fetchFiles = async () => {
try {
const response = await …
```

Optimize FileUpload Component

---

backend/server.py
docs/docs/gpt-researcher/getting-started/linux-deployment.md
frontend/nextjs/components/Settings/Modal.js
gpt_researcher/config/config.py
gpt_researcher/master/agent.py

Changed default DOC_PATH from empty to `./my-docs` everywhere to ensure defaulting to this path when no DOC_PATH is set in .enc file to make it work out of the box.

Partial fix to chat with Documents

---

README-ja_JP.md
README-ko_KR.md
README-zh_CN.md
README.md

Fixes #879.
Details:
- Unify the four versions of README headers
- Fix the broken link to colab in Korean version (see the comment)

Make the README translations more consistent

---

gpt_researcher/utils/llm.py

**Update docstring in `create_chat_completion`**
- Updated the docstring to reflect the correct default values for `temperature` (0.4) and `max_tokens` (4000).

Update docstring to reflect default values for `temperature` and `max_tokens` in `create_chat_completion`

---

frontend/nextjs/app/page.tsx
frontend/nextjs/components/Task/ImageModal.js
frontend/nextjs/components/Task/ImagesCarousel.js
frontend/nextjs/components/Task/LogMessage.tsx
frontend/nextjs/tsconfig.json
gpt_researcher/skills/browser.py

✅ showing images in report

---

backend/server/server_utils.py

Discussed with @ElishaKay over discord about these security fixes.

Sanitize filenames file upload/delete

---

gpt_researcher/retrievers/bing/bing.py

there was a missing import statement in the bing.py file.

fix/bing-retriever: add missing import statement

---

docs/docs/gpt-researcher/frontend/playing-with-webhooks.md

Commit b3c0768328372017225af8f83ce79b733644b355 renamed `getHost.js` to `getHost.ts`. This PR adjusts sources to changes.

update `getHost` reference

---

docs/docs/gpt-researcher/getting-started/introduction.md

Added the youtube tutorial playlist to the documentation.

Added tutorial playlist to documentation

---

docs/docs/gpt-researcher/llms/llms.md
gpt_researcher/memory/embeddings.py

Add support for the Bedrock embedding model, expanding the list of supported embeddings and integrating the necessary imports and initialization logic.

Support Bedrock embedding model

---

backend/report_type/basic_report/basic_report.py
backend/report_type/detailed_report/detailed_report.py
backend/server/server_utils.py
backend/server/websocket_manager.py
gpt_researcher/agent.py
gpt_researcher/document/__init__.py
gpt_researcher/document/online_document.py
gpt_researcher/skills/researcher.py

The hybrid mode currently can only configure document files through the configuration file ./my-docs, which is not very flexible.
Now, it is possible to pass them using the document_urls parameter.

【Added】Enable support for processing online documents in hybrid mode

---

docs/docs/gpt-researcher/llms/llms.md

Change the text to be even more specific about the Azure OpenAI's config.

Update llms.md for Azure OpenAI

---

gpt_researcher/retrievers/tavily/tavily_search.py

https://github.com/assafelovic/gpt-researcher/issues/1111

Update tavily_search.py so TAVILY missing error no longer occurs

---

README-ko_KR.md
README.md

I updated some broken links in README

fix: update broken link in README

---

docs/docs/gpt-researcher/multi_agents/langgraph.md

Update wrong directory nextjs in current example in langgraph.md

fix: update directory nextjs example in langgraph.md

---

gpt_researcher/scraper/beautiful_soup/beautiful_soup.py
gpt_researcher/scraper/browser/browser.py
gpt_researcher/scraper/utils.py

refactor: get text from soup

---

docker-compose.yml

fixed polling param for ubuntu host

---

.env.example

added helpful optional configs for dockerized hosting
Update .env.example

added helpful optional configs for dockerized hosting

---

gpt_researcher/utils/llm.py

Add missing 'temperature' parameter to `llm.py`.
Details: #1154

Fix: missing temperature parameter ( #1154 )

---

docs/docs/gpt-researcher/getting-started/getting-started-with-docker.md
docs/docs/gpt-researcher/llms/supported-llms.md

Update the docker docs + supported LLM page to fix #1126

Update docker doc to add langchain packages

---

gpt_researcher/utils/llm.py

The detailed report was only generating introduction and conclusion.
This is because the subtopic constuction function was broken due to syntax error.
It is fixed and working fine now.

Fixed constuct subtopics

---

.env.example
frontend/index.html
gpt_researcher/document/azure_document_loader.py
gpt_researcher/document/document.py
gpt_researcher/skills/researcher.py
gpt_researcher/utils/enum.py
requirements.txt

Just added the azure-storage option as a document source for the research task. Also please see my raised issue number-#1163

Added the Azure-storage option for document sources.

---

requirements.txt

needed by `uvicorn main:app --reload` following the getting started guide

Update requirements.txt with missing langgraph dep

---

Dockerfile
frontend/index.html
frontend/nextjs/.eslintrc.json
frontend/nextjs/app/page.tsx
frontend/nextjs/components/Footer.tsx
frontend/nextjs/components/Images/ImageModal.jsx
frontend/nextjs/components/ResearchBlocks/elements/InputArea.tsx
frontend/nextjs/components/Settings/ChatBox.tsx
frontend/nextjs/components/Settings/Modal.tsx
frontend/nextjs/components/Task/ResearchForm.tsx
frontend/nextjs/hooks/useAnalytics.ts
frontend/nextjs/hooks/useWebSocket.ts
frontend/nextjs/types/data.ts
gpt_researcher/skills/deep_research.py
requirements.txt

ready for merge 👍
- stabilize docker
- added deep research option to NextJS frontend
- added deep research option to VanillaJS frontend
- fix npm run build

stabilize docker & frontend upgrades

---

backend/report_type/deep_research/main.py
gpt_researcher/actions/query_processing.py
gpt_researcher/agent.py
gpt_researcher/config/variables/default.py
gpt_researcher/skills/deep_research.py

- Fixed issue with crossing token limit in very deep research - max 25,000 words now
- Improved planning stage with conducting initial web search for better planning context
- Introduced new logic to workflow
- Minor bug fixes

Improved overall planning and research performance

---

backend/server/server_utils.py
backend/server/websocket_manager.py
docker-compose.yml
frontend/nextjs/hooks/useWebSocket.ts
gpt_researcher/utils/llm.py

WebSocket was automatically getting closed after 120 seconds from creationg. For tasks that took more than this time, this was an issue. 
This pull request reimplements the comunication between backend and client to make sure that the connection is kept alived, until the proper signal is triggered.

Fix WebSocket timeout issues

---

gpt_researcher/scraper/browser/nodriver_scraper.py

evenly distribute the tabs to different browser instances to improve performance.

perf: load balance nodriver browser scraper tabs

---

requirements.txt

Added langchain-openai to dependencies just to sure on edge cases, as mentioned by @ElishaKay

fix: add langchain-openai to project dependencies (to be safe on edge cases)

---

multi_agents/agents/utils/llms.py

Improves JSON parsing as described in [this comment](https://github.com/assafelovic/gpt-researcher/issues/1137#issuecomment-2695480295).

feature: improve JSON parsing in multi agent setting (#1137)

---

frontend/nextjs/app/globals.css
frontend/nextjs/app/page.tsx
frontend/nextjs/components/ResearchBlocks/elements/InputArea.tsx
frontend/nextjs/components/ResearchSidebar.tsx
frontend/nextjs/components/Settings/App.css
frontend/nextjs/components/Settings/ChatBox.tsx
frontend/nextjs/components/Settings/Modal.tsx
frontend/nextjs/components/Task/ResearchForm.tsx
frontend/nextjs/hooks/useResearchHistory.ts
frontend/nextjs/package.json
frontend/nextjs/types/data.ts

- Added new local storage functionality for research report CRUD operations. This is also a boilerplate for extending to external dbs.
- New sidebar UX with recent history of research reports. 
- Removing reports included.

New Sidebar feature of recent Research History

---

multi_agents/main.py

related to issue mentioned in https://github.com/assafelovic/gpt-researcher/issues/1216
and fix according to the suggestion:
https://github.com/assafelovic/gpt-researcher/issues/1216#issuecomment-2692203134

fix: replace gpt-4o hardcode model in multi-agent with env var.

---

backend/server/server.py
gpt_researcher/config/config.py

Fixed issue https://github.com/assafelovic/gpt-researcher/issues/1268.
removed my-docs folder from being created on server startup and added checks Config init method to check for report source before creating my-docs folder

Fixed issue of my-docs folder being created uncessarily #1268

---

backend/report_type/deep_research/example.py
gpt_researcher/actions/query_processing.py
gpt_researcher/llm_provider/generic/base.py
gpt_researcher/skills/deep_research.py
gpt_researcher/utils/llm.py

Enhancement, Refactoring
___
- Introduced `ReasoningEfforts` enum to standardize reasoning effort levels (`high`, `medium`, `low`).
- Updated reasoning effort values across multiple files to use the new `ReasoningEfforts` enum.
- Added `SUPPORT_REASONING_EFFORT_MODELS` list to track models supporting reasoning effort.
- Refactored `reasoning_effort` parameter handling in `create_chat_completion` to align with supported models.

Streamline reasoning_effort use guide across flows

---

multi_agents/main.py

Fix #1323: Ollama model parsing issue in multi-agent mode

---

docs/docs/gpt-researcher/gptr/config.md
docs/docs/gpt-researcher/llms/llms.md
gpt_researcher/actions/agent_creator.py
gpt_researcher/actions/query_processing.py
gpt_researcher/actions/report_generation.py
gpt_researcher/agent.py
gpt_researcher/config/config.py
gpt_researcher/config/variables/base.py
gpt_researcher/config/variables/default.py
gpt_researcher/context/compression.py
gpt_researcher/llm_provider/generic/base.py
gpt_researcher/prompts.py
gpt_researcher/skills/context_manager.py
gpt_researcher/skills/curator.py
gpt_researcher/skills/researcher.py
gpt_researcher/skills/writer.py
gpt_researcher/utils/enum.py
gpt_researcher/utils/llm.py

This PR is intended to expand the functionality of the researcher to work well with the [IBM Granite](https://ollama.com/library/granite3.2) model family. To do so, it makes two key architectural changes:
* Create the `PromptFamily` abstraction in `prompts.py` so that prompting can be customized to match expected model formats
* Add the ability to set `LLM_KWARGS` and `EMBEDDING_KWARGS` via config when running with `ollama`
* Add abstraction for `PromptFamily`:
* Move all free functions from `prompts.py` into the `PromptFamily` class
* Add the `PromptFamily` enum in `enum.py`
* Add the `get_prompt_family` factory function to instantiate the right prompt family based on the enum or string from the `PromptFamily` enum.
* Plumb `PROMPT_FAMILY` through the `variables` module
* Use the …

IBM Granite

---

gpt_researcher/scraper/firecrawl/firecrawl.py

https://docs.firecrawl.dev/features/scrape

fix firecrawl error: 'ScrapeResponse' object is not subscriptable

---

frontend/index.html
gpt_researcher/llm_provider/generic/base.py

Add "Deep Research" option to selection and fix formatting in base.py

---

backend/server/app.py
backend/server/server.py
main.py

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/assafelovic/gpt-researcher/pull/1400?shareId=1cfd0872-bb4b-46e1-9e0c-4caf3c2f3b9d).

Add WebSocket support to FastAPI server

---

gpt_researcher/mcp/research.py

GPT-Researcher’s MCP integration ignored the MCP response’s structured_content, using only the content field. This caused loss of rich, schema-validated data and reduced research quality. This PR adds first-class support for structured_content with a safe fallback to content.
**Context**
Affected: Linux (Ubuntu 22.04), macOS, Windows
Python: 3.11+
GPT-Researcher: v3.3.3
MCP Implementation: FastMCP
MCP spec (2025-06-18) responses can include`: { "content": [{"type": "text", "text": "Human readable summary"}], "structured_content": { "results": [{"title": "Title", "href": "URL", "body": "Content"}], "count": 25 } }`
**Root Cause**
The retriever processed tool outputs assuming unstructured dict/list or plain text only. No logic existed to extract results from structured_content.results. …

Fix MCP retriever ignoring structured_content; prefer structured data with fallback to content #1480 (solved)
